server:
  port: 30001
cas:
  authn:
        shiro:
              requiredRoles: sso
              location: classpath:shiro.ini
  server:
        name: https://cas.majunwei.com:8443
        prefix: https://cas.majunwei.com:8443/cas
  adminPagesSecurity:
        ip: 127.0.0.1
        loginUrl: https://cas.majunwei.com:8443/cas/login
        service: https://cas.majunwei.com:8443/cas/status/dashboard
        users: file:/etc/cas/config/adminusers.properties
        adminRoles[0]: ROLE_ADMIN
        actuatorEndpointsEnabled: true
  monitor:
        endpoints:
            dashboard:
                enabled: true
                sensitive: true
  #使用json加载注册到CAS上的服务，还可以使用redis／rest等方式
  serviceRegistry:
        json:
            location: classpath:/services
spring:
    http:
        encoding:
              charset: UTF-8
              enabled: true
              force  : true

    cloud:
        bus:
              enabled: false
    thymeleaf:
        encoding: UTF-8
        cache: true
        mode: HTML
    aop:
        auto: true
        proxy-target-class: true
    application:
        name: Jbone CAS
    boot:
        admin:
          client:
            managementUrl: https://cas.majunwei.com:8443/cas/status
            prefer-ip: true
            name: Jbone CAS
            serviceBaseUrl: https://cas.majunwei.com:8443
          url: http://localhost:10002/

endpoints:
    enabled: true
    sensitive: false
#    restart:
#        enabled: false
#    shutdown:
#        enabled: false

management:
    security:
        enabled: true
        roles: ACTUATOR,ADMIN
        sessions: if_required
    context-path: /status
security:
  ignored[0]: /**
#security:
#    basic:
#        authorize-mode: role
#        enabled: false
#       path: /cas/status/**
logging:
    config: classpath:log4j2.xml

eureka:
    client:
        service-url:
            defaultZone: http://localhost:10001/eureka/
ribbon:
    ConnectTimeout: 500
    ReadTimeout: 3000
feign:
    compression:
        request:
            enabled: true
        response:
            enabled: true
