server:
  port: 30001
cas:
  authn:
        #accept:
        #      users: casusertest::Mellon
        shiro:
              requiredRoles: sso
              location: classpath:shiro.ini
  server:
        name: https://cas.majunwei.com:8443
        prefix: https://cas.majunwei.com:8443/cas
  adminPagesSecurity:
        ip: 127.0.0.1

spring:
    http:
        encoding:
              charset: UTF-8
              enabled: true
              force  : true

    cloud:
        bus:
              enabled: false
    thymeleaf:
        encoding: UTF-8
        cache: true
        mode: HTML
    aop:
        auto: true
        proxy-target-class: true
    application:
        name: Jbone CAS

endpoints:
    enabled: false
    sensitive: true
    restart:
        enabled: false
    shutdown:
        enabled: false

management:
    security:
        enabled: true
        roles  : ACTUATOR,ADMIN
        sessions: if_required
    context-path: /status
    add-application-context-header: false

security:
    basic:
        authorize-mode: role
        enabled: false
        path: /cas/status/**
logging:
    config: classpath:log4j2.xml

eureka:
    client:
        service-url:
            defaultZone: http://localhost:10001/eureka/
ribbon:
    ConnectTimeout: 500
    ReadTimeout: 3000
feign:
    compression:
        request:
            enabled: true
        response:
            enabled: true
